// <auto-generated />
namespace CollegeDBEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ResetDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResetDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201803111922001_ResetDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
